//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SingleAppLauncher.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SingleAppLauncher.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This program may work better if you run it as an Administrator.
        ///Would you like to do so?
        ///YES: Run the program as an administrator
        ///NO: Run the program, but do not run it as an administrator
        ///CANCEL: Do not run this program.
        /// </summary>
        internal static string AdminPrompt {
            get {
                return ResourceManager.GetString("AdminPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path cannot be empty..
        /// </summary>
        internal static string EmptyPathError {
            get {
                return ResourceManager.GetString("EmptyPathError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Single App Launcher - {0}
        ///Usage: app.exe [-options]
        ///
        ///Options:
        ///-h               Show this help message.
        ///--p[ath]     Partial path of program to launch
        ///--a[rgs]      Arguments to pass to program
        ///--w[ait]      Time to wait (in milliseconds) before launching the program
        ///
        ///Path and args can be specified in a shortcut or in this program&apos;s config file..
        /// </summary>
        internal static string HelpMessage {
            get {
                return ResourceManager.GetString("HelpMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Single App Launcher.
        /// </summary>
        internal static string MessageBoxCaption {
            get {
                return ResourceManager.GetString("MessageBoxCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: Latest version not found..
        /// </summary>
        internal static string VersionDirectoryNotFoundError {
            get {
                return ResourceManager.GetString("VersionDirectoryNotFoundError", resourceCulture);
            }
        }
    }
}
